name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev libgmock-dev

    - name: Build project
      run: make

    - name: Build tests
      run: make test

    - name: Run tests
      run: make run-tests

    - name: Clean build
      run: make clean

  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev libgmock-dev

    - name: Build with ${{ matrix.compiler }}
      run: |
        CXX=${{ matrix.compiler }} make
        CXX=${{ matrix.compiler }} make test
        ./test_forge